openapi: 3.1.0
info:
  title: Documents API
  version: '1.0'
servers:
  - url: /api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    FirmanteUserDto:
      type: object
      properties:
        userId: { type: number }
        nombre: { type: string }
        puesto: { type: string }
        gerencia: { type: string }
        responsabilidadId: { type: number }
    ResponsablesFirmaDto:
      type: object
      properties:
        elabora:
          $ref: '#/components/schemas/FirmanteUserDto'
        revisa:
          type: array
          items: { $ref: '#/components/schemas/FirmanteUserDto' }
        aprueba:
          type: array
          items: { $ref: '#/components/schemas/FirmanteUserDto' }
    CreateCuadroFirmaDto:
      type: object
      required: [titulo, descripcion, version, codigo, empresa_id, createdBy]
      properties:
        titulo: { type: string }
        descripcion: { type: string }
        version: { type: string }
        codigo: { type: string }
        empresa_id: { type: string }
        createdBy: { type: string }
    UpdateCuadroFirmaDto:
      type: object
      properties:
        titulo: { type: string }
        descripcion: { type: string }
        version: { type: string }
        codigo: { type: string }
        empresa_id: { type: string }
        createdBy: { type: string }
        responsables: { $ref: '#/components/schemas/ResponsablesFirmaDto' }
    FirmaCuadroDto:
      type: object
      required: [userId, nombreUsuario, cuadroFirmaId, responsabilidadId, nombreResponsabilidad]
      properties:
        userId: { type: string }
        nombreUsuario: { type: string }
        cuadroFirmaId: { type: string }
        responsabilidadId: { type: string }
        nombreResponsabilidad: { type: string }
    UpdateEstadoAsignacionDto:
      type: object
      required: [idCuadroFirma, idEstadoFirma, nombreEstadoFirma, userId, nombreUser, observaciones]
      properties:
        idCuadroFirma: { type: number }
        idEstadoFirma: { type: number }
        nombreEstadoFirma: { type: string }
        userId: { type: number }
        nombreUser: { type: string }
        observaciones: { type: string }
paths:
  /documents/cuadro-firmas:
    post:
      summary: Crear cuadro de firmas
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                responsables:
                  type: string
                titulo: { type: string }
                descripcion: { type: string }
                version: { type: string }
                codigo: { type: string }
                empresa_id: { type: string }
                createdBy: { type: string }
      responses:
        '201': { description: creado }
  /documents/cuadro-firmas/{id}:
    get:
      summary: Detalle de cuadro de firmas
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: ok }
  /documents/cuadro-firmas/firmantes/{id}:
    get:
      summary: Firmantes del cuadro
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: ok }
  /documents/cuadro-firmas/historial/{id}:
    get:
      summary: Historial de estados
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
        - in: query
          name: page
          schema: { type: number }
        - in: query
          name: limit
          schema: { type: number }
      responses:
        '200': { description: ok }
  /documents/cuadro-firmas/{id}:
    patch:
      summary: Actualizar cuadro de firmas
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCuadroFirmaDto'
      responses:
        '200': { description: actualizado }
  /documents/cuadro-firmas/documento/{id}:
    patch:
      summary: Reemplazar documento
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                userId: { type: string }
                observaciones: { type: string }
      responses:
        '202': { description: reemplazado }
  /documents/cuadro-firmas/firmar:
    post:
      summary: Firmar documento
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                userId: { type: string }
                nombreUsuario: { type: string }
                cuadroFirmaId: { type: string }
                responsabilidadId: { type: string }
                nombreResponsabilidad: { type: string }
      responses:
        '200': { description: firmado }
  /documents/cuadro-firmas/estado:
    patch:
      summary: Cambiar estado del cuadro
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEstadoAsignacionDto'
      responses:
        '200': { description: actualizado }
  /documents/cuadro-firmas/by-user/{userId}:
    get:
      summary: Asignaciones del usuario
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema: { type: string }
        - in: query
          name: page
          schema: { type: number }
        - in: query
          name: limit
          schema: { type: number }
        - in: query
          name: estado
          schema: { type: string }
        - in: query
          name: search
          schema: { type: string }
        - in: query
          name: empresa
          schema: { type: number }
        - in: query
          name: sort
          schema: { type: string }
      responses:
        '200': { description: ok }
  /documents/cuadro-firmas/documentos/supervision:
    get:
      summary: Documentos para supervisión
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema: { type: number }
        - in: query
          name: limit
          schema: { type: number }
        - in: query
          name: estado
          schema: { type: string }
        - in: query
          name: search
          schema: { type: string }
        - in: query
          name: empresa
          schema: { type: number }
        - in: query
          name: sort
          schema: { type: string }
      responses:
        '200': { description: ok }
  /documents/cuadro-firmas/documento-url:
    get:
      summary: Obtener URL prefirmada
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: fileName
          required: true
          schema: { type: string }
      responses:
        '200': { description: ok }
